local Core = MidnightSensei.Core

Core.RegisterSpec(7, {
    className = "Shaman",

    -- Elemental (Midnight 12.0 pass — April 2026; spell snapshot + verify audit April 2026)
    -- Removed:  Primordial Wave (375982) — pruned in Midnight 12.0; functionality merged into
    --           Voltaic Blaze which handles AoE Flame Shock automatically
    -- Removed:  Fire Elemental (198067) — no longer a manual summon in Midnight 12.0;
    --           auto-generated by Ascendance as part of Stormbringer design
    -- Removed:  60103 from rotationalSpells — this is Lava Lash (Enhancement), not Lava Burst
    -- Removed:  Earth Shock (8042) from priority notes — not in spell list or talent tree in Midnight 12.0
    -- Removed:  Flame Shock (470411) — not available to Elemental in Midnight 12.0; Enhancement only
    --           Voltaic Blaze (470057) is the Elemental Shaman's Flame Shock replacement
    -- Added:    Earthquake (462620) as talentGated rotational — confirmed Elemental Talent nodeID 80985
    -- Added:    Elemental Blast (117014) as talentGated rotational — confirmed Elemental Talent nodeID 80984
    -- Added:    Voltaic Blaze (470057) as talentGated rotational — nodeID 81007; Flame Shock replacement for Elemental
    -- Added:    Lightning Bolt (188196) as baseline rotational — confirmed spell list; primary filler
    -- Tempest (454009) — confirmed PASSIVE nodeID 94892; not tracked
    -- Not added: Lava Surge (77756) to procBuffs — confirmed in Elemental Spell List as player aura
    --            but needs in-game C_UnitAuras.GetPlayerAuraBySpellID verification before adding
    -- Confirmed: Lava Burst cast ID = 51505 (UNIT_SPELLCAST_SUCCEEDED verified in-game, fired 7x)
    -- Kept:     Stormkeeper (191634), Ascendance (114050) confirmed in Elemental Talents
    [1] = {
        name = "Elemental", role = "DPS",
        resourceType = 11, resourceLabel = "MAELSTROM", overcapAt = 90,
        majorCooldowns = {
            { id = 191634, label = "Stormkeeper", expectedUses = "on CD"         },  -- confirmed nodeID 80988
            { id = 114050, label = "Ascendance",  expectedUses = "burst windows" },  -- confirmed nodeID 80989; auto-summons Fire Elemental in Midnight 12.0
        },
        -- uptimeBuffs intentionally empty: Flame Shock is a target debuff,
        -- not detectable via C_UnitAuras.GetPlayerAuraBySpellID.
        uptimeBuffs = {},
        rotationalSpells = {
            { id = 188196, label = "Lightning Bolt",  minFightSeconds = 15 },                          -- confirmed spell list; primary filler
            { id = 51505,  label = "Lava Burst",      minFightSeconds = 15 },                          -- non-PASSIVE ACTIVE nodeID 103598; cast ID confirmed in-game
            { id = 462620, label = "Earthquake",      minFightSeconds = 30, talentGated = true },      -- non-PASSIVE ACTIVE nodeID 80985
            { id = 117014, label = "Elemental Blast", minFightSeconds = 20, talentGated = true },      -- non-PASSIVE ACTIVE nodeID 80984
            { id = 470057, label = "Voltaic Blaze",   minFightSeconds = 20, talentGated = true },      -- nodeID 81007; Flame Shock replacement for Elemental — DoT applicator
            -- Flame Shock (470411) removed — Enhancement only in Midnight 12.0; Voltaic Blaze replaces it for Elemental
            -- Tempest (454009) removed — confirmed PASSIVE nodeID 94892
        },
        priorityNotes = {
            "Voltaic Blaze is the Flame Shock replacement for Elemental — maintain the DoT when talented",
            "Lava Burst on cooldown — always consume Lava Surge procs immediately",
            "Lightning Bolt as primary filler — empowered by Stormkeeper for burst",
            "Stormkeeper before empowered Lightning Bolt casts for maximum burst",
            "Elemental Blast to spend Maelstrom (single target, when talented) — avoid overcap at 90",
            "Earthquake to spend Maelstrom on AoE — avoid overcap at 90",
            "Ascendance for burst — automatically summons Fire Elemental in Midnight 12.0",
        },
        scoreWeights = { cooldownUsage = 35, activity = 40, resourceMgmt = 25 },
        sourceNote = "Midnight 12.0 verified against spell snapshot + talent tree 112 nodes (April 2026)",
    },

    -- Enhancement (Midnight 12.0 PASSIVE audit — April 2026)
    -- Feral Spirit: was 51533 — talent tree confirms 469314 PASSIVE. Removed entirely.
    -- Ascendance: was 114051 — not in Enhancement talent tree at all. Removed.
    -- Primordial Wave (375982): not in Enhancement talent tree or spell list. Removed.
    -- Maelstrom Weapon procBuff: was 344179 — spell list confirms 187880. Corrected.
    -- Surging Totem (444995) added to majorCooldowns — non-PASSIVE ACTIVE nodeID 94877
    -- Crash Lightning (187874) added to rotational — non-PASSIVE ACTIVE nodeID 80974
    -- Lava Lash (60103) added to rotational — non-PASSIVE ACTIVE nodeID 109389
    -- Voltaic Blaze (470057) added as talentGated rotational — non-PASSIVE ACTIVE nodeID 80954
    [2] = {
        name = "Enhancement", role = "DPS",
        resourceType = 11, resourceLabel = "MAELSTROM", overcapAt = 140,
        majorCooldowns = {
            { id = 384352, label = "Doom Winds",    expectedUses = "burst windows",  talentGated = true },  -- non-PASSIVE ACTIVE nodeID 80959
            { id = 197214, label = "Sundering",     expectedUses = "on CD (talent)", talentGated = true },  -- non-PASSIVE ACTIVE nodeID 80975
            { id = 444995, label = "Surging Totem", expectedUses = "on CD (talent)", talentGated = true },  -- non-PASSIVE ACTIVE nodeID 94877
            -- Feral Spirit (51533/469314) removed — PASSIVE
            -- Ascendance (114051) removed — not in Enhancement talent tree
            -- Primordial Wave (375982) removed — not in Midnight 12.0
        },
        uptimeBuffs = {},
        procBuffs = {
            { id = 187880, label = "Maelstrom Weapon", maxStackTime = 20 },  -- confirmed spell list (was 344179)
        },
        rotationalSpells = {
            { id = 187874, label = "Crash Lightning", minFightSeconds = 15 },                     -- non-PASSIVE ACTIVE nodeID 80974
            { id = 60103,  label = "Lava Lash",       minFightSeconds = 15 },                     -- non-PASSIVE ACTIVE nodeID 109389
            { id = 470057, label = "Voltaic Blaze",   minFightSeconds = 20, talentGated = true }, -- non-PASSIVE ACTIVE nodeID 80954
        },
        priorityNotes = {
            "Maintain Flame Shock on targets for Hot Hand procs and Lava Lash damage (not directly tracked)",
            "Spend Maelstrom Weapon at 5+ stacks — spend at 10 before any cap",
            "Stormstrike on cooldown — primary builder and damage source",
            "Lava Lash to spread Flame Shock in multi-target and spend Maelstrom stacks",
            "Crash Lightning before AoE pulls to apply the ground effect",
            "Doom Winds at peak Maelstrom / burst window when talented",
            "Surging Totem on cooldown when talented — significant throughput increase",
            "Avoid Maelstrom Weapon overcap — spend with Lightning Bolt or Elemental Blast",
        },
        scoreWeights = { cooldownUsage = 30, procUsage = 30, activity = 25, resourceMgmt = 15 },
        sourceNote = "Midnight 12.0 PASSIVE audit against full Enhancement talent tree 102 nodes (April 2026)",
    },

    -- Restoration (Midnight 12.0 pass — April 2026)
    -- Removed:  Cloudburst Totem (157153) — pruned from Restoration in Midnight 12.0
    --           as part of spec simplification removing high-timing-skill buttons
    -- Removed:  Ancestral Guidance (108281) — removed from game in Midnight (patch 11.1.0 / Feb 25 2025)
    -- Removed:  Healing Tide Totem (108280) — confirmed removed from Resto in Midnight 12.0
    -- Also pruned by Blizzard (not tracked): Earthen Wall Totem, Ancestral Protection Totem,
    --           Wellspring, High Tide, Tidebringer, Undulation, Master of the Elements,
    --           Mana Tide, Tide Turner, Spiritwalker's Tidal Totem
    -- Added:    Surging Totem (444995) — new Midnight 12.0 talent, confirmed Resto Talent nodeID 94877
    --           replaces Cloudburst Totem as the signature throughput cooldown
    -- Added:    Unleash Life (73685) to majorCooldowns — confirmed Resto Talent nodeID 92677
    --           pre-heal amplifier, strong on-cooldown usage
    -- Added:    Call of the Ancestors (443450) as talentGated cooldown — confirmed nodeID 94888
    -- Added:    rotationalSpells: Riptide, Chain Heal, Healing Rain — all confirmed in Resto files
    -- Kept:     Spirit Link Totem (98008) confirmed nodeID 81041
    --           Ascendance (114052) confirmed nodeID 81032
    --           Healing Rain (73920) moved to rotationalSpells (maintained on CD, not a burst CD)
    [3] = {
        name = "Restoration", role = "HEALER",
        resourceType = 0,
        majorCooldowns = {
            { id = 98008,  label = "Spirit Link Totem", expectedUses = "dangerous health disparities" },  -- non-PASSIVE ACTIVE nodeID 81041
            { id = 444995, label = "Surging Totem",     expectedUses = "before damage windows"        },  -- non-PASSIVE ACTIVE nodeID 94877
            { id = 73685,  label = "Unleash Life",      expectedUses = "on CD — pre-heal amplifier"   },  -- non-PASSIVE ACTIVE nodeID 92675
            { id = 114052, label = "Ascendance",        expectedUses = "emergency throughput"         },  -- non-PASSIVE ACTIVE nodeID 81032
            -- Call of the Ancestors (443450) removed — confirmed PASSIVE nodeID 94888
        },
        uptimeBuffs = {},
        rotationalSpells = {
            { id = 61295,  label = "Riptide",      minFightSeconds = 15 },  -- confirmed nodeID 81027; core maintenance HoT
            { id = 1064,   label = "Chain Heal",   minFightSeconds = 20 },  -- confirmed in Resto files; primary group heal
            { id = 73920,  label = "Healing Rain",  minFightSeconds = 30 },  -- confirmed nodeID 81040; high efficiency on stacked groups
        },
        healerMetrics = { targetOverheal = 30, targetActivity = 80, targetManaEnd = 15 },
        priorityNotes = {
            "Keep Riptide rolling on 2-3 injured targets at all times — primary HoT maintenance",
            "Surging Totem before predictable raid damage windows for burst throughput",
            "Unleash Life on cooldown — pre-heal amplifier, use before Chain Heal or Healing Rain",
            "Healing Rain on stacked groups — keep it active, high mana efficiency",
            "Chain Heal for group damage when multiple targets are injured",
            "Spirit Link Totem to equalize dangerous health imbalances across the raid",
            "Ascendance for emergency throughput — not a maintenance cooldown",
            "Avoid excessive overheal — cast slightly later on targets above 70% health",
        },
        scoreWeights = { cooldownUsage = 25, efficiency = 30, activity = 25, responsiveness = 20 },
        sourceNote = "Midnight 12.0 PASSIVE audit against full Restoration talent tree 110 nodes (April 2026)",
    },
})
